{{- if .Values.gandiApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: gandi-credentials
  namespace: {{ .Values.certManager.namespace | quote }}
  labels:
    {{- include "cert-manager-webhook-gandi.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{ .Values.gandiApiToken | toString | b64enc | quote }}
{{- end }}